#!/usr/bin/env python3
""" Skeleton Implementation of Project 2 for NEU CS3700"""

import argparse, socket, time, json, select, struct, math, ipaddress
from ipaddress import IPv4Network
from routerUtils import RouterUtils

parser = argparse.ArgumentParser(description='route packets')
parser.add_argument('asn', type=int, help="AS Number")
parser.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
args = parser.parse_args()


##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"

##########################################################################################

class Router:
    """ Your Router """

    def __init__(self, networks):
        self.routes = {}
        self.updates = {}
        self.relations = {}
        self.sockets = {}
        self.forwardingInfo = {}

        for relationship in networks:
            network, relation = relationship.split("-")
            self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
            self.sockets[network].setblocking(0)
            self.sockets[network].connect(network)
            self.relations[network] = relation

    def forward(self, srcif, packet):
        ports = RouterUtils.allPossible(packet["dst"], self.routes)
        ports = RouterUtils.filterRelationships(ports, srcif, self.relations)
        sock = RouterUtils.getLongestPrefix(ports, self.sockets)
        if sock == None:
            RouterUtils.sendNoRoute(srcif, packet, self.sockets)
        else:
            RouterUtils.forwardData(sock, packet)
        return False

    def coalesce(self):
        while(True):
            aggregate = RouterUtils.getCoalesce(self.forwardingInfo)
            if (aggregate == None):
                break
            RouterUtils.handleCoalesce(aggregate[0], aggregate[1], self.routes, self.forwardingInfo)
        return False

    def update(self, srcif, packet):
        if (self.updates.get(srcif) == None):
            self.updates[srcif] = [packet]
        else:
            self.updates[srcif].append(packet)

        networkAddress = RouterUtils.calculateNetAddress(packet["msg"]["network"], packet["msg"]["netmask"])

        if (self.routes.get(networkAddress) == None):
            self.routes[networkAddress] = packet["src"]
        elif (RouterUtils.isBestPath(packet, self.forwardingInfo[networkAddress][0])):
            self.routes[networkAddress] = packet["src"]
        RouterUtils.placeUpdateInOrder(networkAddress, packet, self.routes, self.forwardingInfo)
        RouterUtils.forwardUpdate(srcif, packet, args.asn, self.relations, self.sockets)
        self.coalesce()

        return False

        del packet["msg"]["ASPath"][-1]

    def revoke(self, srcif, packet):
        self.routes = {}
        self.forwardingInfo = {}

        for i in range(len(packet["msg"])):
            network = packet["msg"][i]["network"]
            netmask = packet["msg"][i]["netmask"]

            toDelete = []

            for j in range(len(self.updates[srcif])):
                if (self.updates[srcif][j]["msg"]["network"] == network) and (self.updates[srcif][j]["msg"]["netmask"] == netmask):
                    toDelete.append(j)

            for k in range(len(toDelete)):
                self.updates[srcif].pop(toDelete[k])


        for key in self.updates:
            for val in self.updates[key]:
                networkAddress = RouterUtils.calculateNetAddress(val["msg"]["network"], val["msg"]["netmask"])

                if (self.routes.get(networkAddress) == None):
                    self.routes[networkAddress] = val["src"]
                elif (RouterUtils.isBestPath(val, self.forwardingInfo[networkAddress][0])):
                    self.routes[networkAddress] = val["src"]
                RouterUtils.placeUpdateInOrder(networkAddress, val, self.routes, self.forwardingInfo)
                self.coalesce()

        RouterUtils.forwardRevoke(srcif, packet, self.relations, self.sockets)
        return True

    def build_forwarding_table(forwardingInfo):
        fowardingTable = []
        for key in forwardingInfo:
            for item in forwardingInfo[key]:
                fowardingTable.append({'network': key.split('/')[0], 'netmask': item['msg']['netmask'], 'peer': item['src']})
        return forwardTable

    def dump(self, srcif, packet):
        forwardingTable = build_forwarding_table(self.forwardingInfo)
        msg = {'src': packet['dst'], 'dst': packet['src'], 'type': 'table', 'msg': forwardingTable}
        self.sock_send(self.sockets[srcif], msg)
        return True

    def handle_packet(self, srcif, packet):
        if packet['type'] == DATA:
            self.forward(srcif, packet)
        elif packet['type'] == DUMP:
            self.dump(srcif, packet)
        elif packet['type'] == UPDT:
            self.update(srcif, packet)
        elif packet['type'] == RVKE:
            self.revoke(srcif, packet)
        else:
            return False
        return True

    def sock_send(self, sock, msg):
        sock.send(json.dumps(msg).encode('ASCII'))

    def send_error(self, conn, msg):
        self.sock_send(conn, msg)
        return

    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                try:
                    k = conn.recv(65535)
                except:
                    return
                if k:
                    for sock in self.sockets:
                        if self.sockets[sock] == conn:
                            srcif = sock
                    msg = json.loads(k)
                    if not self.handle_packet(srcif, msg):
                        self.send_error(conn, msg)
                else:
                    return
        return

if __name__ == "__main__":
    router = Router(args.networks)
    router.run()
