#!/usr/bin/env python3
""" Skeleton Implementation of Project 2 for NEU CS3700 """

import argparse
import json
import select
import socket

import ipaddress
from ipaddress import IPv4Network


##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"



##########################################################################################

class Router:
  """ Your Router """

  def __init__(self, asn, networks):
    # the asn from command line
    self.asn = asn[0]
    # key: network ip address we can send to -> val: best port ip to send out
    self.routes = {}
    # key: network ip address we can send to -> val: list of update (ordered by best path)
    self.routesAndUpdates = {}
    # key: port/src ip address -> val: [update messages]
    self.updates = {}
    # key: port/src ip addres -> val: [revoke messages]
    self.revokes = {}
    # key: port/src ip address -> val: one of CUST PEER PROV
    self.relations = {}
    # key: port/src ip address -> val: literally the socket
    self.sockets = {}
    # key: portion of netmask address -> val: number of bits
    self.maskConvTable = {"255": 8, "254": 7, "252": 6, "248": 5, "240": 4, "224": 3, "192": 2, "128": 1, "0": 0}


    for relationship in networks:
      network, relation = relationship.split("-")
      self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
      self.sockets[network].setblocking(0)
      self.sockets[network].connect(network)
      self.relations[network] = relation


  def get_route(self, srcif, daddr):
    """ Select the best route for a given address """
    # TODO
    peer = None
    routes = self.lookup_routes(daddr)
    # Rules go here
    if routes:
      # 1. Highest Preference
      routes = self.get_highest_preference(routes)
      # 2. Self Origin
      routes = self.get_self_origin(routes)
      # 3. Shortest ASPath
      routes = self.get_shortest_as_path(routes)
      # 4. EGP > IGP > UNK
      routes = self.get_origin_routes(routes)
      # 5. Lowest IP Address
      # TODO
      # Final check: enforce peering relationships
      routes = self.filter_relationships(srcif, routes)
    return self.sockets[peer] if peer else None



  def forward(self, srcif, packet):
    """ Forward a data packet """

    # find all possible networks from forwarding table
    ports = self.allPossible(packet["dst"])

    # enforce peering relationships
    ports = self.filterRelationships(ports, srcif)

    # get the one with the highest netmask
    sock = self.getLongestPrefix(ports)

    # send to the socket or send no route back to source
    if sock == None:
      self.sendNoRoute(srcif, packet)
    else:
      self.forwardData(sock, packet)

    return False


  # forwards data to the sock
  def forwardData(self, sock, packet):
    # pack into json and encode
    packetJSON = json.dumps(packet)
    packetJSON = packetJSON.encode("ASCII")
    # send
    sock.send(packetJSON)

    return True

  # sends a no route back to the source
  def sendNoRoute(self, srcif, packet):
    # split source ip into array, modify last digit to 1 (us)
    srcifSplit = srcif.split(".")
    srcifSplit[-1] = "1"
    # put back together
    srcUs = ".".join(srcifSplit)

    # create a no route message, pack into json, encode, send
    noRouteMessage = {"src": srcUs, "dst": packet["src"], "type": "no route", "msg": {}}
    packetJSON = json.dumps(noRouteMessage)
    packetJSON = packetJSON.encode("ASCII")
    self.sockets[srcif].send(packetJSON)

    return False

  # returns socket for the highest prefix or none for nothing
  def getLongestPrefix(self, ports):
    # initialize socket
    sock = None

    # initialize variables
    longestPref = 0
    longestNetwork = ""

    # iterate through matches, find longest cidr
    for key in ports:
      pref = int(key.split("/")[1])

      if pref > longestPref:
        longestPref = pref
        longestNetwork = key

    # none were found
    if longestPref == 0:
      return None

    # get the right socket
    sock = self.sockets[ports[longestNetwork]]

    return sock

  # filter based on neigbor relationships
  def filterRelationships(self, ports, srcif):
    # accumulator
    keysToRemove = []
    # if sender is not customer and reciever is not customer dont send
    if self.relations[srcif] != CUST:
      for key in ports:
        if self.relations[ports[key]] != CUST:
          keysToRemove.append(key)

    # remove invalid relationships
    for key in keysToRemove:
      del ports[key]

    return ports


  # get all network matches
  def allPossible(self, dstAddress):
    # key: network address -> val: port ip address
    ports = {}

    for key in self.routes:
      # network, mask = knownNetworks[i].split("/")
      # splitNetwork = knownNetworks[i].split(".")
      if ipaddress.ip_address(dstAddress) in ipaddress.ip_network(key):
        ports[key] = self.routes.get(key)

    return ports

  def coalesce(self):
    """ coalesce any routes that are right next to each other """
    # TODO (this is the most difficult task, save until last)

    while(True):
      aggregate = self.getCoalesce()
      if (aggregate == None):

        break

      self.handleCoalesce(aggregate[0], aggregate[1])

    return False

  # returns true if the two cidrs can be aggregated just based on cidr
  def canCoalesceKey(self, key1, key2):
    # split keys into ips and cidr vals
    ip1, cidr1 = key1.split("/")
    ip2, cidr2 = key2.split("/")


    # if the cidrs match then continue
    if (cidr1 == cidr2):
      # split into array of binary
      bin1 = list(''.join(format(int(x), '08b') for x in ip1.split(".")))
      bin2 = list(''.join(format(int(x), '08b') for x in ip2.split(".")))

      # get index, we know cidrs are the same value, so same index for both
      idx = int(cidr1) - 1


      # check for numerical adjacency
      if ((bin1[idx] == '1') and (bin2[idx] == '0')):
        return True
      if ((bin1[idx] == '0') and (bin2[idx] == '1')):
        return True


    return False


  # returns true if the update messages have the same attributes
  def sameAttributes(self, msg1, msg2):
    # compare all attributes and return
    return ((msg1['src'] == msg2['src']) and
            (msg1['msg']['localpref'] == msg2['msg']['localpref']) and
            (msg1['msg']['selfOrigin'] == msg2['msg']['selfOrigin']) and
            (msg1['msg']['ASPath'] == msg2['msg']['ASPath']) and
            (msg1['msg']['origin'] == msg2['msg']['origin']))



  # returns [first cidr, second cidr] if something can coalesce, otherwise none
  def getCoalesce(self):
    for key1, value1 in self.routesAndUpdates.items():
      for key2, value2 in self.routesAndUpdates.items():

        # if networks are adjacent, return them
        if (self.canCoalesceKey(key1, key2)):
          for msg1 in value1:
            for msg2 in value2:
              if self.sameAttributes(msg1, msg2):
                return [key1, key2]

    return None

  # do the coalesce
  def handleCoalesce(self, key1, key2):

    # GET THE NEW KEY, SET TO []
    ip, cidr = key1.split("/")
    binary = list(''.join(format(int(x), '08b') for x in ip.split(".")))
    binary[int(cidr) - 1] = '0'
    newipbinary = ''.join(binary)
    groupsOfEight = [newipbinary[i: i + 8] for i in range(0, len(newipbinary), 8)]
    for i in range(len(groupsOfEight)):
      groupsOfEight[i] = str(int(groupsOfEight[i], 2))

    # get new ip, cidr, key, and netmask
    newIp = '.'.join(groupsOfEight)
    newCidr = str(int(cidr) - 1)

    newKey = newIp + '/' + newCidr

    newNetmask = str(IPv4Network(newKey).netmask)

    # save old versions of update list
    updates1 = self.routesAndUpdates[key1]
    updates2 = self.routesAndUpdates[key2]

    # iterate through and find matching updates
    for i in range(len(updates1)):
      for j in range(len(updates2)):
        if self.sameAttributes(updates1[i], updates2[j]):
          # create the new update message, remove the old ones
          newMsg = updates1[i]
          newMsg['msg']['network'] = newIp
          newMsg['msg']['netmask'] = newNetmask
          self.placeUpdateInOrder(newKey, newMsg)
          updates1.pop(i)
          updates2.pop(j)

          # set the old update lists to the new ones
          self.routesAndUpdates[key1] = updates1
          self.routesAndUpdates[key2] = updates2

          # set routing table to best possible ports
          self.routes[newKey] = self.routesAndUpdates[newKey][0]["src"]

          if len(self.routesAndUpdates[key1]) == 0:
            del self.routes[key1]
            del self.routesAndUpdates[key1]
          else:
            self.routes[key1] = self.routesAndUpdates[key1][0]["src"]

          if len(self.routesAndUpdates[key2]) == 0:
            del self.routes[key2]
            del self.routesAndUpdates[key2]
          else:
            self.routes[key2] = self.routesAndUpdates[key2][0]["src"]

          return True


    print("NO COALESCE HANDLED, ERROR IN GET COALESCE")
    return False

  # handles getting an update message WITHOUT SENDING MESSAGE, checks if new path is better
  # than old, updates forwarding table accordingly
  # ALSO DOES NOT ADD TO THE UPDATE TABLE
  # FOR INTERNAL USE ONLY IN REVOKE V2
  def updateNoMSG(self, srcif, packet):
    """ handle update packets """

    # get the network address by using the netmask
    networkAddress = self.calculateNetAddress(packet["msg"]["network"], packet["msg"]["netmask"])

    # check if there is an entry in the forwarding table yet
    # replace the entry if new path is the best path
    if (self.routes.get(networkAddress) == None):
      self.routes[networkAddress] = packet["src"]
    elif (self.isBestPath(packet, self.routesAndUpdates[networkAddress][0])):
      self.routes[networkAddress] = packet["src"]
      # place updates in order from best to worst
    self.placeUpdateInOrder(networkAddress, packet)

    # coalesce
    self.coalesce()

    return False

  # handles getting an update message, checks if new path is better
  # than old, updates forwarding table accordingly
  def update(self, srcif, packet):
    """ handle update packets """
    # check if updates map has seen the source ip yet
    # adds the packet message to the list of updates
    if (self.updates.get(srcif) == None):
      self.updates[srcif] = [packet]
    else:
      self.updates[srcif].append(packet)

    # get the network address by using the netmask
    networkAddress = self.calculateNetAddress(packet["msg"]["network"], packet["msg"]["netmask"])

    # check if there is an entry in the forwarding table yet
    # replace the entry if new path is the best path
    if (self.routes.get(networkAddress) == None):
      self.routes[networkAddress] = packet["src"]
    elif (self.isBestPath(packet, self.routesAndUpdates[networkAddress][0])):
      self.routes[networkAddress] = packet["src"]
      # place updates in order from best to worst
    self.placeUpdateInOrder(networkAddress, packet)

    # forward the update
    self.forwardUpdate(srcif, packet)

    # coalesce
    self.coalesce()

    return False

  # places an update message in order in the list of update messages (best first)
  def placeUpdateInOrder(self, networkAddress, packet):
    # MAKE A COPY OF THE PACKET TO AVOID MUTATION DURING COALESCE
    newPacket = {"type": "update", "src": packet["src"], "dst": packet["dst"],
                 "msg": {"network": packet["msg"]["network"], "netmask": packet["msg"]["netmask"],
                         "localpref": packet["msg"]["localpref"], "ASPath": packet["msg"]["ASPath"],
                         "origin": packet["msg"]["origin"], "selfOrigin": packet["msg"]["selfOrigin"]}}
    # first check for no key yet
    if self.routesAndUpdates.get(networkAddress) == None:
      self.routesAndUpdates[networkAddress] = [newPacket]
      return True
    # place in the new update in order of best route
    for i in range(len(self.routesAndUpdates[networkAddress])):
      if self.isBestPath(newPacket, self.routesAndUpdates[networkAddress][i]):
        self.routesAndUpdates[networkAddress].insert(i, newPacket)
        return True

    # was the worst so far, goes at end
    self.routesAndUpdates[networkAddress].append(newPacket)

    return True


  # calculates a network address using the given netmask
  def calculateNetAddress(self, address, mask):
    # accumulator, total number of bits for netmask
    maskVal = 0

    # split netmask into an array
    maskArr = mask.split(".")
    # accumulate the bits for the netmask
    for i in range(len(maskArr)):
      if (self.maskConvTable.get(maskArr[i]) == None):
        print("BIT MASK DOESNT EXIST: %s" % maskArr[i])
        raise KeyError
      maskVal += self.maskConvTable[maskArr[i]]

    return address + "/" + str(maskVal)


  # Forwards an udapte packet to the correct ports
  def forwardUpdate(self, srcif, packet):
    # add ourselves to the as path
    newPacket = {"type": "update", "src": None, "dst": None, "msg": packet["msg"]}
    newPacket["msg"]["ASPath"].append(self.asn)
    ogSrc = packet["src"]
    # check if sender was a customer
    if (self.relations[ogSrc] == CUST):
      # send to all other sockets
      for key in self.sockets:
        if key != srcif:
          self.sendPacketHelper(newPacket, key)

    # must have beena PEER or PROV
    else:
      for key in self.relations:
        if (self.relations[key] == CUST) and (key != srcif):
          self.sendPacketHelper(newPacket, key)

    # undo modification of aspath
    del packet["msg"]["ASPath"][-1]


    # compares the new path with the old path
    # returns true if new is better
    # false if old is better
  def isBestPath(self, newPacket, oldPacket):
    msg = 'msg'
    localpref = 'localpref'
    selfOrigin = 'selfOrigin'
    ASPATH = 'ASPath'
    origin = 'origin'


    # CHECK FOR HIGHEST LOCAL PATH
    if (newPacket[msg][localpref] > oldPacket[msg][localpref]):
      return True
    elif (newPacket[msg][localpref] < oldPacket[msg][localpref]):
      return False
    # CHECK FOR ORIGIN
    if (newPacket[msg][selfOrigin] and not(oldPacket[msg][selfOrigin])):
      return True
    elif (not(newPacket[msg][selfOrigin]) and (oldPacket[msg][selfOrigin])):
      return False

    # CHECK ASPATH
    if (len(newPacket[msg][ASPATH]) < len(oldPacket[msg][ASPATH])):
      return True
    elif (len(newPacket[msg][ASPATH]) > len(oldPacket[msg][ASPATH])):
      return False

    # CHECK ORIGIN IGP
    if ((newPacket[msg][origin] == "IGP") and (not(oldPacket[msg][origin]) == "IGP")):
      return True
    elif ((not(newPacket[msg][origin]) == "IGP") and (oldPacket[msg][origin] == "IGP")):
      return False

    # CHECK ORIGIN EGP
    if ((newPacket[msg][origin] == "EGP") and (not(oldPacket[msg][origin]) == "EGP")):
      return True
    elif ((not(newPacket[msg][origin]) == "EGP") and (oldPacket[msg][origin] == "EGP")):
      return False

    # CHECK ORIGIN UNK
    if ((newPacket[msg][origin] == "UNK") and (not(oldPacket[msg][origin]) == "UNK")):
      return True
    elif ((not(newPacket[msg][origin]) == "UNK") and (oldPacket[msg][origin] == "UNK")):
      return False

    # RETURN LOWER IP ADDRESS

    newIP = ipaddress.IPv4Address(newPacket['src'])
    oldIP = ipaddress.IPv4Address(oldPacket['src'])
    return (newIP < oldIP)

  # revoke that deals with deaggregation
  # deletes forwarding tables
  # rebuilds from the stored update messages.
  # deletes update messages that are revoked.
  def revokeV2(self, packet, srcif):
    self.routes = {}
    self.routesAndUpdates = {}


    # iterate and remove all necessary update messages
    for i in range(len(packet["msg"])):
      network = packet["msg"][i]["network"]
      netmask = packet["msg"][i]["netmask"]

      # store idxs to delete
      toDelete = []

      # iterate through, if network address matches then we need to remove it
      for j in range(len(self.updates[srcif])):
        if (self.updates[srcif][j]["msg"]["network"] == network) and (self.updates[srcif][j]["msg"]["netmask"] == netmask):
          toDelete.append(j)

      # delete store idxs
      for k in range(len(toDelete)):
        self.updates[srcif].pop(toDelete[k])

    # parse all updates and add them to the forwarding table
    for key in self.updates:
      for val in self.updates[key]:
        self.updateNoMSG(val["src"], val)

    self.forwardRevoke(srcif, packet)
    return True



  def revoke(self, packet, srcif):
    """ handle revoke packets """
    # store the revoke message
    # print("FORWARD TABLE BEFORE REVOKE: %s" % json.dumps(self.routesAndUpdates, indent=4, separators=(',', ': ')))
    if (self.revokes.get(srcif) == None):
      self.revokes[srcif] = [packet]
    else:
      self.revokes[srcif].append(packet)

    # iterate thorugh revoke list, remove them from possible paths
    for i in range(len(packet["msg"])):
      self.removePath(packet["msg"][i], srcif)


    # print("FORWARD TABLE AFTER REVOKE: %s" % json.dumps(self.routesAndUpdates, indent=4, separators=(',', ': ')))
    # forward the revocation
    self.forwardRevoke(srcif, packet)

    return True

  # remove one element from the list of revokes
  def removePath(self, network, srcif):
    # get CIDR format
    networkAddress = self.calculateNetAddress(network["network"], network["netmask"])

    # exit/do nothing if there are no paths to this network yet
    if self.routesAndUpdates.get(networkAddress) == None:
      return True

    n = len(self.routesAndUpdates[networkAddress])
    i = 0
    # if the update came from the source of the revoke message, remove it
    while i < n:
      if self.routesAndUpdates[networkAddress][i]["src"] == srcif:
        del self.routesAndUpdates[networkAddress][i]
        n -= 1
      else:
        i += 1

    # if length of list is now 0, remove the keys, exit function
    if len(self.routesAndUpdates[networkAddress]) == 0:
      del self.routesAndUpdates[networkAddress]
      del self.routes[networkAddress]
      return True


    # if the best path so far is out the port that wants to revoke, find a new best path
    # since routesAndUpdates is sorted and all from
    # revoke port have been removed, first entry must be the best path
    if self.routes[networkAddress] == srcif:
      self.routes[networkAddress] = self.routesAndUpdates[networkAddress][0]["src"]

    return True

  # checks for possible deaggregation and handles it accordingly, does not remove old
  # routing table entry (handled later in remove path)
  # def checkDeaggregate


  # Forwards an udapte packet to the correct ports
  def forwardRevoke(self, srcif, packet):
    newPacket = {"type": "revoke", "src": None, "dst": None, "msg": packet["msg"]}
    ogSrc = packet["src"]
    # check if sender was a customer
    if (self.relations[ogSrc] == CUST):
      # send to all other sockets
      for key in self.sockets:
        if key != srcif:
          self.sendPacketHelper(newPacket, key)

    # must have been a PEER or PROV
    else:
      for key in self.relations:
        if (self.relations[key] == CUST) and (key != srcif):
          self.sendPacketHelper(newPacket, key)


  # helper method to send update and revoke packets
  def sendPacketHelper(self, newPacket, key):
    # modify the packet (switch dst and src)
    newPacket["dst"] = key
    keyTemp = key.split(".")
    keyTemp[-1] = "1"
    keyTemp = ".".join(keyTemp)
    newPacket["src"] = keyTemp
    # pack into json, encode, send
    packetJSON = json.dumps(newPacket)
    packetJSON = packetJSON.encode("ASCII")
    self.sockets[key].send(packetJSON)

    return True


  def dump(self, packet, srcif):
    """ handles dump table requests """
    # array accumulator to hold routes
    fowardTable = []
    # iterate through table, print in correct format
    for key in self.routesAndUpdates:
      network, cidr = key.split("/")
      for i in range(len(self.routesAndUpdates[key])):
        netmask = self.routesAndUpdates[key][i]["msg"]["netmask"]
        peer = self.routesAndUpdates[key][i]["src"]
        entry = {"network": network, "netmask": netmask, "peer": peer}
        fowardTable.append(entry)


    dumpMsg = {"src": packet["dst"], "dst": packet["src"], "type": "table", "msg": fowardTable}
    packetJSON = json.dumps(dumpMsg)
    packetJSON = packetJSON.encode("ASCII")
    self.sockets[srcif].send(packetJSON)
    return True

  def handle_packet(self, srcif, packet):
    """ dispatches a packet """

    # debug statement below
    # print("PACKET RECIEVED: %s" % json.dumps(packet, indent=4, separators=(',', ': ')))

    msgType = packet['type']
    # handle each type of message
    if (msgType == 'update'):
      self.update(srcif, packet)
      return True

    if (msgType == 'data'):
      self.forward(srcif, packet)
      return True

    if (msgType == 'dump'):
      self.dump(packet, srcif)
      return True

    if (msgType == 'revoke'):
      self.revokeV2(packet, srcif)
      return True

    return False

  def send_error(self, conn, msg):
    msg = json.dumps(msg)
    msg = msg.encode("ASCII")
    conn.send(msg)
    return False

  def run(self):
    """ main loop for the router """
    while True:
      socks = select.select(self.sockets.values(), [], [], 0.1)[0]
      for conn in socks:
        try:
          k = conn.recv(65535)
        except:
          # either died on a connection reset, or was SIGTERM's by parent
          return
        if k:
          for sock in self.sockets:
            if self.sockets[sock] == conn:
              srcif = sock
          msg = json.loads(k)
          if not self.handle_packet(srcif, msg):
            self.send_error(conn, msg)
        else:
          return

if __name__ == "__main__":
  PARSER = argparse.ArgumentParser(description='route packets')
  PARSER.add_argument('asn', metavar="asn", type=int, nargs=1, help="asn")
  PARSER.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
  ARGS = PARSER.parse_args()
  Router(ARGS.asn, ARGS.networks).run()
