#!/usr/bin/env python3
""" Skeleton Implementation of Project 2 for NEU CS3700"""

import argparse
import json
import select
import socket

import ipaddress
from ipaddress import IPv4Network

from routerUtils import RouterUtils


##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"



##########################################################################################

class Router:
  """ Your Router """

  def __init__(self, asn, networks):
    self.asn = asn[0]
    self.routes = {}
    self.routesAndUpdates = {}
    self.updates = {}
    self.revokes = {}
    self.relations = {}
    self.sockets = {}
    self.maskConvTable = {"255": 8, "254": 7, "252": 6, "248": 5, "240": 4, "224": 3, "192": 2, "128": 1, "0": 0}


    for relationship in networks:
      network, relation = relationship.split("-")
      self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
      self.sockets[network].setblocking(0)
      self.sockets[network].connect(network)
      self.relations[network] = relation

  def forward(self, srcif, packet):
    ports = self.allPossible(packet["dst"])
    ports = self.filterRelationships(ports, srcif)
    sock = self.getLongestPrefix(ports)
    if sock == None:
      self.sendNoRoute(srcif, packet)
    else:
      self.forwardData(sock, packet)

    return False

  def forwardData(self, sock, packet):
    packetJSON = json.dumps(packet)
    packetJSON = packetJSON.encode("ASCII")
    sock.send(packetJSON)
    return True

  def sendNoRoute(self, srcif, packet):
    srcifSplit = srcif.split(".")
    srcifSplit[-1] = "1"
    srcUs = ".".join(srcifSplit)
    noRouteMessage = {"src": srcUs, "dst": packet["src"], "type": "no route", "msg": {}}
    packetJSON = json.dumps(noRouteMessage)
    packetJSON = packetJSON.encode("ASCII")
    self.sockets[srcif].send(packetJSON)

    return False

  def getLongestPrefix(self, ports):
    sock = None
    longestPref = 0
    longestNetwork = ""
    for key in ports:
      pref = int(key.split("/")[1])

      if pref > longestPref:
        longestPref = pref
        longestNetwork = key
    if longestPref == 0:
      return None
    sock = self.sockets[ports[longestNetwork]]
    return sock

  def filterRelationships(self, ports, srcif):
    keysToRemove = []
    if self.relations[srcif] != CUST:
      for key in ports:
        if self.relations[ports[key]] != CUST:
          keysToRemove.append(key)

    for key in keysToRemove:
      del ports[key]

    return ports

  def allPossible(self, dstAddress):
    ports = {}

    for key in self.routes:
      if ipaddress.ip_address(dstAddress) in ipaddress.ip_network(key):
        ports[key] = self.routes.get(key)

    return ports

  def coalesce(self):
    while(True):
      aggregate = self.getCoalesce()
      if (aggregate == None):
        break
      self.handleCoalesce(aggregate[0], aggregate[1])
    return False

  def canCoalesceKey(self, key1, key2):
    ip1, cidr1 = key1.split("/")
    ip2, cidr2 = key2.split("/")
    if (cidr1 == cidr2):
      bin1 = list(''.join(format(int(x), '08b') for x in ip1.split(".")))
      bin2 = list(''.join(format(int(x), '08b') for x in ip2.split(".")))
      idx = int(cidr1) - 1

      if ((bin1[idx] == '1') and (bin2[idx] == '0')):
        return True
      if ((bin1[idx] == '0') and (bin2[idx] == '1')):
        return True


    return False

  def sameAttributes(self, msg1, msg2):
    return ((msg1['src'] == msg2['src']) and
            (msg1['msg']['localpref'] == msg2['msg']['localpref']) and
            (msg1['msg']['selfOrigin'] == msg2['msg']['selfOrigin']) and
            (msg1['msg']['ASPath'] == msg2['msg']['ASPath']) and
            (msg1['msg']['origin'] == msg2['msg']['origin']))

  def getCoalesce(self):
    for key1, value1 in self.routesAndUpdates.items():
      for key2, value2 in self.routesAndUpdates.items():
        if (self.canCoalesceKey(key1, key2)):
          for msg1 in value1:
            for msg2 in value2:
              if self.sameAttributes(msg1, msg2):
                return [key1, key2]

    return None

  def handleCoalesce(self, key1, key2):
    ip, cidr = key1.split("/")
    binary = list(''.join(format(int(x), '08b') for x in ip.split(".")))
    binary[int(cidr) - 1] = '0'
    newipbinary = ''.join(binary)
    groupsOfEight = [newipbinary[i: i + 8] for i in range(0, len(newipbinary), 8)]
    for i in range(len(groupsOfEight)):
      groupsOfEight[i] = str(int(groupsOfEight[i], 2))

    newIp = '.'.join(groupsOfEight)
    newCidr = str(int(cidr) - 1)

    newKey = newIp + '/' + newCidr

    newNetmask = str(IPv4Network(newKey).netmask)
    updates1 = self.routesAndUpdates[key1]
    updates2 = self.routesAndUpdates[key2]

    for i in range(len(updates1)):
      for j in range(len(updates2)):
        if self.sameAttributes(updates1[i], updates2[j]):
          newMsg = updates1[i]
          newMsg['msg']['network'] = newIp
          newMsg['msg']['netmask'] = newNetmask
          self.placeUpdateInOrder(newKey, newMsg)
          updates1.pop(i)
          updates2.pop(j)
          self.routesAndUpdates[key1] = updates1
          self.routesAndUpdates[key2] = updates2
          self.routes[newKey] = self.routesAndUpdates[newKey][0]["src"]

          if len(self.routesAndUpdates[key1]) == 0:
            del self.routes[key1]
            del self.routesAndUpdates[key1]
          else:
            self.routes[key1] = self.routesAndUpdates[key1][0]["src"]

          if len(self.routesAndUpdates[key2]) == 0:
            del self.routes[key2]
            del self.routesAndUpdates[key2]
          else:
            self.routes[key2] = self.routesAndUpdates[key2][0]["src"]

          return True
    return False

  def updateNoMSG(self, srcif, packet):
    networkAddress = self.calculateNetAddress(packet["msg"]["network"], packet["msg"]["netmask"])

    if (self.routes.get(networkAddress) == None):
      self.routes[networkAddress] = packet["src"]
    elif (self.isBestPath(packet, self.routesAndUpdates[networkAddress][0])):
      self.routes[networkAddress] = packet["src"]
    self.placeUpdateInOrder(networkAddress, packet)
    self.coalesce()

    return False

  def update(self, srcif, packet):
    if (self.updates.get(srcif) == None):
      self.updates[srcif] = [packet]
    else:
      self.updates[srcif].append(packet)

    networkAddress = self.calculateNetAddress(packet["msg"]["network"], packet["msg"]["netmask"])

    if (self.routes.get(networkAddress) == None):
      self.routes[networkAddress] = packet["src"]
    elif (self.isBestPath(packet, self.routesAndUpdates[networkAddress][0])):
      self.routes[networkAddress] = packet["src"]
    self.placeUpdateInOrder(networkAddress, packet)
    self.forwardUpdate(srcif, packet)
    self.coalesce()

    return False

  def placeUpdateInOrder(self, networkAddress, packet):
    newPacket = {"type": "update", "src": packet["src"], "dst": packet["dst"],
                 "msg": {"network": packet["msg"]["network"], "netmask": packet["msg"]["netmask"],
                         "localpref": packet["msg"]["localpref"], "ASPath": packet["msg"]["ASPath"],
                         "origin": packet["msg"]["origin"], "selfOrigin": packet["msg"]["selfOrigin"]}}
    if self.routesAndUpdates.get(networkAddress) == None:
      self.routesAndUpdates[networkAddress] = [newPacket]
      return True

    for i in range(len(self.routesAndUpdates[networkAddress])):
      if self.isBestPath(newPacket, self.routesAndUpdates[networkAddress][i]):
        self.routesAndUpdates[networkAddress].insert(i, newPacket)
        return True

    self.routesAndUpdates[networkAddress].append(newPacket)

    return True

  def calculateNetAddress(self, address, mask):
    maskVal = 0
    maskArr = mask.split(".")
    for i in range(len(maskArr)):
      if (self.maskConvTable.get(maskArr[i]) == None):
        print("BIT MASK DOESNT EXIST: %s" % maskArr[i])
        raise KeyError
      maskVal += self.maskConvTable[maskArr[i]]

    return address + "/" + str(maskVal)

  def forwardUpdate(self, srcif, packet):
    newPacket = {"type": "update", "src": None, "dst": None, "msg": packet["msg"]}
    newPacket["msg"]["ASPath"].append(self.asn)
    ogSrc = packet["src"]
    if (self.relations[ogSrc] == CUST):
      for key in self.sockets:
        if key != srcif:
          RouterUtils.sendPacketHelper(newPacket, key, self.sockets)

    else:
      for key in self.relations:
        if (self.relations[key] == CUST) and (key != srcif):
          RouterUtils.sendPacketHelper(newPacket, key, self.sockets)

    del packet["msg"]["ASPath"][-1]

  def isBestPath(self, newPacket, oldPacket):
    msg = 'msg'
    localpref = 'localpref'
    selfOrigin = 'selfOrigin'
    ASPATH = 'ASPath'
    origin = 'origin'

    if (newPacket[msg][localpref] > oldPacket[msg][localpref]):
      return True
    elif (newPacket[msg][localpref] < oldPacket[msg][localpref]):
      return False

    if (newPacket[msg][selfOrigin] and not(oldPacket[msg][selfOrigin])):
      return True
    elif (not(newPacket[msg][selfOrigin]) and (oldPacket[msg][selfOrigin])):
      return False

    if (len(newPacket[msg][ASPATH]) < len(oldPacket[msg][ASPATH])):
      return True
    elif (len(newPacket[msg][ASPATH]) > len(oldPacket[msg][ASPATH])):
      return False

    if ((newPacket[msg][origin] == "IGP") and (not(oldPacket[msg][origin]) == "IGP")):
      return True
    elif ((not(newPacket[msg][origin]) == "IGP") and (oldPacket[msg][origin] == "IGP")):
      return False

    if ((newPacket[msg][origin] == "EGP") and (not(oldPacket[msg][origin]) == "EGP")):
      return True
    elif ((not(newPacket[msg][origin]) == "EGP") and (oldPacket[msg][origin] == "EGP")):
      return False

    if ((newPacket[msg][origin] == "UNK") and (not(oldPacket[msg][origin]) == "UNK")):
      return True
    elif ((not(newPacket[msg][origin]) == "UNK") and (oldPacket[msg][origin] == "UNK")):
      return False

    newIP = ipaddress.IPv4Address(newPacket['src'])
    oldIP = ipaddress.IPv4Address(oldPacket['src'])
    return (newIP < oldIP)

  def revokeV2(self, packet, srcif):
    self.routes = {}
    self.routesAndUpdates = {}

    for i in range(len(packet["msg"])):
      network = packet["msg"][i]["network"]
      netmask = packet["msg"][i]["netmask"]

      toDelete = []

      for j in range(len(self.updates[srcif])):
        if (self.updates[srcif][j]["msg"]["network"] == network) and (self.updates[srcif][j]["msg"]["netmask"] == netmask):
          toDelete.append(j)

      for k in range(len(toDelete)):
        self.updates[srcif].pop(toDelete[k])
    for key in self.updates:
      for val in self.updates[key]:
        self.updateNoMSG(val["src"], val)

    self.forwardRevoke(srcif, packet)
    return True



  def revoke(self, packet, srcif):
    if (self.revokes.get(srcif) == None):
      self.revokes[srcif] = [packet]
    else:
      self.revokes[srcif].append(packet)

    for i in range(len(packet["msg"])):
      self.removePath(packet["msg"][i], srcif)

    self.forwardRevoke(srcif, packet)

    return True

  def removePath(self, network, srcif):
    networkAddress = self.calculateNetAddress(network["network"], network["netmask"])
    if self.routesAndUpdates.get(networkAddress) == None:
      return True

    n = len(self.routesAndUpdates[networkAddress])
    i = 0
    while i < n:
      if self.routesAndUpdates[networkAddress][i]["src"] == srcif:
        del self.routesAndUpdates[networkAddress][i]
        n -= 1
      else:
        i += 1

    if len(self.routesAndUpdates[networkAddress]) == 0:
      del self.routesAndUpdates[networkAddress]
      del self.routes[networkAddress]
      return True

    if self.routes[networkAddress] == srcif:
      self.routes[networkAddress] = self.routesAndUpdates[networkAddress][0]["src"]

    return True

  def forwardRevoke(self, srcif, packet):
    newPacket = {"type": "revoke", "src": None, "dst": None, "msg": packet["msg"]}
    ogSrc = packet["src"]
    if (self.relations[ogSrc] == CUST):
      for key in self.sockets:
        if key != srcif:
          RouterUtils.sendPacketHelper(newPacket, key, self.sockets)
    else:
      for key in self.relations:
        if (self.relations[key] == CUST) and (key != srcif):
          RouterUtils.sendPacketHelper(newPacket, key, self.sockets)

  def dump(self, packet, srcif):
    fowardTable = []
    for key in self.routesAndUpdates:
      network, cidr = key.split("/")
      for i in range(len(self.routesAndUpdates[key])):
        netmask = self.routesAndUpdates[key][i]["msg"]["netmask"]
        peer = self.routesAndUpdates[key][i]["src"]
        entry = {"network": network, "netmask": netmask, "peer": peer}
        fowardTable.append(entry)


    dumpMsg = {"src": packet["dst"], "dst": packet["src"], "type": "table", "msg": fowardTable}
    packetJSON = json.dumps(dumpMsg)
    packetJSON = packetJSON.encode("ASCII")
    self.sockets[srcif].send(packetJSON)
    return True

  def handle_packet(self, srcif, packet):
    msgType = packet['type']
    if (msgType == 'update'):
      self.update(srcif, packet)
      return True

    if (msgType == 'data'):
      self.forward(srcif, packet)
      return True

    if (msgType == 'dump'):
      self.dump(packet, srcif)
      return True

    if (msgType == 'revoke'):
      self.revokeV2(packet, srcif)
      return True

    return False

  def send_error(self, conn, msg):
    msg = json.dumps(msg)
    msg = msg.encode("ASCII")
    conn.send(msg)
    return False

  def run(self):
    while True:
      socks = select.select(self.sockets.values(), [], [], 0.1)[0]
      for conn in socks:
        try:
          k = conn.recv(65535)
        except:
          return
        if k:
          for sock in self.sockets:
            if self.sockets[sock] == conn:
              srcif = sock
          msg = json.loads(k)
          if not self.handle_packet(srcif, msg):
            self.send_error(conn, msg)
        else:
          return

if __name__ == "__main__":
  PARSER = argparse.ArgumentParser(description='route packets')
  PARSER.add_argument('asn', metavar="asn", type=int, nargs=1, help="asn")
  PARSER.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
  ARGS = PARSER.parse_args()
  router = Router(ARGS.asn, ARGS.networks)
  router.run()
