#!/usr/bin/env python3
import socket
import sys
import ssl

# Variables
PORT = 27993
HOSTNAME = ''
NUID = 0
args = sys.argv
use_ssl = False

# Arg logic
need_hostname = True
check_port = False
for i in range(1, len(args)):
    arg = args[i]
    if arg == '-p':
        check_port = True
    elif arg == '-s':
        use_ssl = True
    elif check_port:
        check_port = False
        PORT = int(arg)
    elif need_hostname:
        need_hostname = False
        HOSTNAME = arg
    else:
        NUID = arg

if use_ssl and PORT == 27993:
  PORT = 27994

# Make the socket; make the socket an ssl socket if necessary
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOSTNAME, PORT))
if use_ssl:
    context = ssl.SSLContext(ssl.PROTOCOL_TLS)
    s = context.wrap_socket(s, server_side=False, server_hostname=HOSTNAME)

# Send the HELLO message through the socket
s.send('cs3700fall2020 HELLO {}\n'.format(NUID).encode())

# Helper variables
bits = 1024
finding = True
flag = ''
count = 0

# FIND message problem solving loop
while finding:
    more_data = True
    data = ''

    # Continue recv until a \n character comes
    while more_data:
        this_data = s.recv(bits).decode()
        data += this_data
        more_data = '\n' not in this_data

    data_pieces = data.split(' ')
    message = data_pieces[1]

    if message == 'FIND':
        symbol = data_pieces[2]
        symbols = data_pieces[3]
        count = symbols.count(symbol)
        response = 'cs3700fall2020 COUNT {}\n'.format(str(count))
        s.send(response.encode())

    elif message == 'BYE':
        finding = False
        flag = data_pieces[2]

# Flag
print(flag)
s.close()
